### ISSUE TITLE
Add `http::Response` support

### ISSUE THREAD

**Issue by dora-gt** [chridou/http-api-problem#14]
Hi,

I just came across your implementation when I was implementing a bit similar function. Do you have any plan to support `http::Response`? Because we use `warp`, it would be great if this crate  supports `http::Response`. We could also consider creating a PR to do so.

**Comment by chridou** [comment]
Hi!

Is this still required? We could do it.

**Comment by chridou** [comment]
@dora-gt support for warp has been explicitly added
