### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by thomaseizinger** [chridou/http-api-problem#16]
It would be nice if this project would follow [keep-a-changelog](https://keepachangelog.com/en/1.0.0/).

We use dependabot in our repository and without a changelog, it is very hard to see what changed between two versions: https://github.com/comit-network/comit-rs/pull/1833

Following the keep-a-changelog format will also require git tags for each version, which is nice in general because it allows downstream developers to glance over what changed between to versions.

Dependabot is a nice assistant here because it creates a link to the diff for you (from you current version to the one you are updating to).

See this PR as an example: https://github.com/comit-network/comit-rs/pull/1834

Thanks for considering <3

**Comment by chridou** [comment]
Hi! 

That is a great idea. I'm completely open to this!

**Comment by chridou** [comment]
I will do this next.
