### ISSUE TITLE
Rocket support ?

### ISSUE THREAD

**Issue by kyasu1** [chridou/http-api-problem#24]
Hi ! 

Rocket support seems to be removed in the latest version. Is there any plan to support it again ?

Thanks.

**Comment by chridou** [comment]
Yes. I plan to readd it. Just need to think a bit about the features since it is nightly only.

**Comment by kyasu1** [comment]
Ah I see. Some users prefer or need stable versions only.

At least for for my needs, just pasting the deleted codes solved the issue. Maybe adding them as a part of [rocket_contrib](https://api.rocket.rs/v0.4/rocket_contrib/) is a way to go.

Thanks.

**Comment by klochowicz** [comment]
Hi! I've run into this issue as well when trying to use your library (we're trying out Rocket for our latest project, as it works on stable now). I've created a PR in case the nightly compiler was the biggest roadblock for re-adding it (#34 ).

**Comment by chridou** [comment]
Solved with https://github.com/chridou/http-api-problem/pull/34

Thank you!
