### ISSUE TITLE
Depend on the `http` crate?

### ISSUE THREAD

**Issue by thomaseizinger** [chridou/http-api-problem#3]
The HTTP crate (https://crates.io/crates/http) defines common types around the HTTP world like a `StatusCode` enum.

Using that one instead of defining a separate one would improve interoperability with other web-frameworks that depend on `http` already. (For example, `warp`)

Eventually, it might even be possible to get rid of all the feature-flags if the ecosystem catches up with using types from the http-crate.

Would you accept a PR that refactors the crate to use the `http` crate and the types from it?

**Comment by chridou** [comment]
That would be really great and I would thankfully accept a PR. Maybe later one could even think of using the status codes etc. from the http crate.

**Comment by thomaseizinger** [comment]
Well, using at least the statuscodes from there would be the main thing I'd
do as part of that PR :)

**Comment by chridou** [comment]
That would be really cool.

**Comment by chridou** [comment]
Yes.
