### ISSUE TITLE
Add `source`, `field` getters for `ApiError`.

### ISSUE THREAD

**Issue by damooo** [chridou/http-api-problem#39]
Currently `ApiError`'s `source` and fields cannot be accessed in any way. Thus it prohibits acting based on source error, or any custom fields added by middleware. It would be useful if corresponding getters are provided.

**Comment by chridou** [comment]
Hi! 

Thanks for your feedback!

`source` is provided by by the `Error` impl.

All fields are public so you can modify the fields as you please or am I maybe getting something wrong?


I'm considering to also add `http::extensions` so that typed values can be carried by the `ApiError`

**Comment by chridou** [comment]
Sorry, a bit late. Was looking at the builder ;-)

**Comment by chridou** [comment]
There is a draft PR (WIP): https://github.com/chridou/http-api-problem/pull/41
